
export const DOCUMENT_TYPES = [
  { value: 'bet', label: 'Betänkande' },
  { value: 'dir', label: 'Kommittédirektiv' },
  { value: 'ds', label: 'Departementsserien' },
  { value: 'eprotokoll', label: 'EU-nämndens protokoll' },
  { value: 'eundok', label: 'EU-nämndens dokument' },
  { value: 'eunprot', label: 'EU-nämndens uppteckning' },
  { value: 'everkber', label: 'EU-nämndens verksamhetsberättelse' },
  { value: 'f-lista', label: 'Föredragningslista' },
  { value: 'fpm', label: 'Fakta-PM om EU-förslag' },
  { value: 'fr', label: 'Skriftlig fråga' },
  { value: 'frs', label: 'Svar på skriftlig fråga' },
  { value: 'frsrdg', label: 'Framställning / redogörelse' },
  { value: 'ip', label: 'Interpellation' },
  { value: 'kf-lista', label: 'Kallelse och föredragningslista' },
  { value: 'kom', label: 'EU-förslag' },
  { value: 'komm', label: 'Kommittéberättelse' },
  { value: 'ku-anm', label: 'KU-anmälning' },
  { value: 'kusprot', label: 'KU:s särskilda protokoll' },
  { value: 'mot', label: 'Motion' },
  { value: 'prop', label: 'Proposition' },
  { value: 'prot', label: 'Protokoll' },
  { value: 'rfr', label: 'Rapport från riksdagen' },
  { value: 'rir', label: 'Riksrevisionens granskningsrapport' },
  { value: 'rskr', label: 'Riksdagsskrivelse' },
  { value: 'SFS', label: 'Svensk författningssamling' },
  { value: 'skflista', label: 'Särskild kallelse- och föredragningslista' },
  { value: 'skrsam', label: 'EU-nämndens skriftliga samråd' },
  { value: 'sou', label: 'Statens offentliga utredning' },
  { value: 't-lista', label: 'Talarlista' },
  { value: 'uprotokoll', label: 'Utskottens protokoll' },
  { value: 'urf', label: 'Utredning från Riksdagsförvaltningen' },
  { value: 'utskdok', label: 'Utskottsdokument' },
  { value: 'utskottsmöte', label: 'Utskottens kallelse- och föredragningslista' },
  { value: 'uverkber', label: 'Utskottens verksamhetsberättelse' },
  { value: 'vpnbeslut', label: 'Valprövningsnämndens beslut' },
  { value: 'yttr', label: 'Yttrande' }
];

export const COMMITTEES = [
  { value: 'AU', label: 'Arbetsmarknadsutskottet' },
  { value: 'BoU', label: 'Bostadsutskottet' },
  { value: 'CU', label: 'Civilutskottet' },
  { value: 'EU', label: 'EES-utskottet' },
  { value: 'eun', label: 'EU-nämnden' },
  { value: 'FiU', label: 'Finansutskottet' },
  { value: 'FöU', label: 'Försvarsutskottet' },
  { value: 'JoU', label: 'Jordbruksutskottet' },
  { value: 'JuU', label: 'Justitieutskottet' },
  { value: 'KU', label: 'Konstitutionsutskottet' },
  { value: 'KrU', label: 'Kulturutskottet' },
  { value: 'LU', label: 'Lagutskottet' },
  { value: 'MjU', label: 'Miljö- och jordbruksutskottet' },
  { value: 'NU', label: 'Näringsutskottet' },
  { value: 'CKrU', label: 'Sammansatta civil- och kulturutskottet' },
  { value: 'JuSoU', label: 'Sammansatta justitie- och socialutskottet' },
  { value: 'KUU', label: 'Sammansatta konstitutions- och utrikesutskottet' },
  { value: 'UFöU', label: 'Sammansatta utrikes- och försvarsutskottet' },
  { value: 'UMJU', label: 'Sammansatta utrikes- och miljö- och jordbruksutskottet' },
  { value: 'USoU', label: 'Sammansatta utrikes- och socialutskottet' },
  { value: 'SkU', label: 'Skatteutskottet' },
  { value: 'SfU', label: 'Socialförsäkringsutskottet' },
  { value: 'SoU', label: 'Socialutskottet' },
  { value: 'TU', label: 'Trafikutskottet' },
  { value: 'UbU', label: 'Utbildningsutskottet' },
  { value: 'UU', label: 'Utrikesutskottet' }
];

export const SORT_OPTIONS = [
  { value: 'rel', label: 'Relevans' },
  { value: 'datum', label: 'Datum' },
  { value: 'systemdatum', label: 'Systemdatum' },
  { value: 'bet', label: 'Beteckning' },
  { value: 'debattdag', label: 'Debattdag' },
  { value: 'debattdagtid', label: 'Debattdagtid' },
  { value: 'beslutsdag', label: 'Beslutsdag' }
];
