
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqhpbclqvhjcyrgvgaon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxaHBiY2xxdmhqY3lyZ3ZnYW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDA1NDEsImV4cCI6MjA2NDIxNjU0MX0.cUnZNOYFmfS-dK5GPhNZjCkvduXzR8DyswWfE0bIG1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
